### ISSUE TITLE
Consider a new release?

### ISSUE THREAD

**Issue by feschber** [ids1024/reis#5] opened 2023-12-20 14:16 UTC
Release 0.1.0 does not yet include the `tokio` feature, which I find very useful.

Would be great if there was a new release with this feature included.
I'm currently using the git version.

**Comment by ids1024** [comment] 2023-12-20 16:39
You may also find the `reis::tokio::ei_handshake` function I added last week helpful.

I actually didn't remember that the `tokio` module was added after 0.1, so that's good to note. With https://github.com/ids1024/reis/commit/b27f8eeeae40e88b4cc5970d30aa42af25afb5fe, the next release is a breaking change (though only slightly), so I'll have to think if there are any other breaking changes I'd be making soon.

I've just recently tested Reis with the RemoteDesktop/InputCapture portals on Gnome 45 (rather than just a fake test server) so I'm just starting to figure out how it could provide a somewhat higher-level API. (Definitely easy to iterate on an API design using Reis as a client rather than trying to integrate a server in a Wayland compositor.)

**Comment by feschber** [comment] 2023-12-20 17:42
Good to hear! Some higher level event type like in the c library would definitely be great.

**Comment by ids1024** [comment] 2023-12-20 18:06
Yeah. I'm thinking to should be fairly simple to map events to a higher level event enum. With accessors for the device/seat like `ei_event` has. Most events just map one-to-one, while seat/device have `done` events, so the higher-level `SeatAdded` event would let you access all the device properties set before that.

If that wraps per-event structs, that would provide an API like the `input` (libinput bindings) crate. I'll need something like that with eis to cleanly integrate server support for sender contexts into Smithay.

Could probably be a little more type-safe than libei by distinguishing at a type level between sender/receive contexts. Not sure about device methods. The way ei uses "capabilities" rather than device types makes it a little less natural to represent a type that only offers the methods supported on the device.

**Comment by feschber** [comment] 2023-12-20 18:28
There is two more things, I noticed:

1. Maybe it is possible to throw an error if a capability was requested that is not included in the devices selected through the remote desktop session. (when such an interface is added).

2. It would be helpful to have a way to retrieve the device from an interface, (currently one has to remember the device that emitted the interface event together with the device.

I guess the second thing will be sorted when a higher level event api is in place.

**Comment by ids1024** [comment] 2023-12-22 05:39
`ei_seat_bind_capabilities()` says "Calling this function for a capability that does not exist on the seat is permitted (but obviously a noop)". I think it makes sense to provide the same behavior in the higher level API. Applications can bind all the capabilities they are potentially interested in, and also query if a capability is supported.

Accessing the device behind an event, and any interfaces for a given device, would by part of the higher-level API as well.

There's a bit of boilerplate that can't quite be generated dealing with each event, but now that I have an idea how I want it to work I'm making progress on a higher-level event type: https://github.com/ids1024/reis/compare/event?expand=1.

**Comment by ids1024** [comment] 2023-12-22 06:27
I've merged an initial version of that, though it still needs some fixes and refinement.

The `tokio` module is also somewhat preliminary since I want to also support `async-io`, and it should proably poll for writeability if there is any data to flush. Then with the higher level event API, lets see how minimal async uses of reis can be.

But some of these things could be in a later release.

**Comment by feschber** [comment] 2024-01-03 14:32
FYI: I tried it out and it is working great so far!
Now I need to figure out how to get ashpd to connect to multiple portals at once without panicing ...

The error types (HandshakeError) should probably implement std::error::Error so that they are compatible with e.g. anyhow.

Also: Is there no way for a libei client to "release" an ongoing input capture? I have read all of the protocol documentation several times and to me it seems like the only way to hand control of a device back to the compositor is through the input capture portal interface... [org.freedesktop.portal.InputCapture.html#org-freedesktop-portal-inputcapture-release](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.InputCapture.html#org-freedesktop-portal-inputcapture-release)

**Comment by ids1024** [comment] 2024-01-03 16:09
Yeah, the error type need more information, and implementations of `Display` and `Error`.

I'm fairly happy with the higher `EiEvent` and `EisRequest` types I've added, though the conversion logic still needs to handle `destroyed` events, and some other things. And I'm not sure how best to name and organize things. I guess those could be `reis::Event` and `reis::Request` in contrast to the lower level `reis::ei::Event` and `reis::eis::Request`. Or maybe the generated lower level types could be in a submodule like `reis::ei::proto::Request`. Hm.

`libei` just doesn't expose generated APIs in the public API of the library. But that's not the case with reis for now.

> Now I need to figure out how to get ashpd to connect to multiple portals at once without panicing ...

Not sure why that's happening, without seeing what error it shows, but I'd open an issue on ashpd with a minimal reproduction.

> Also: Is there no way for a libei client to "release" an ongoing input capture? I have read all of the protocol documentation several times and to me it seems like the only way to hand control of a device back to the compositor is through the input capture portal interface...

Yeah, that seems to be how libei is designed to be used. Libei mostly just provides a channel for input events (in either direction) while the portal API is needed for other operations like that. Libei isn't concerned with the fact that input is "captured" by the client, just that the server is sending input events to the client.

**Comment by feschber** [comment] 2024-01-03 21:14
Figured out the ashpd issue: I was trying to create the proxies simultaneously: [ashpd/issues/185](https://github.com/bilelmoussaoui/ashpd/issues/185)

> Yeah, that seems to be how libei is designed to be used. Libei mostly just provides a channel for input events (in either direction) while the portal API is needed for other operations like that. Libei isn't concerned with the fact that input is "captured" by the client, just that the server is sending input events to the client.

Thanks for confirming!

As for the Struct names, Imo having a Type for Requests is better than the "C" way of generating function calls.
The naming seems fine. I dont think it matters too much whether its `eis::Request` or `eis::proto::Request` as long as the meaning is clear.

`proto` is a good choice I would say, even though it breaks backwards compatibility

**Comment by ids1024** [comment] 2024-01-04 03:26
In particular that's mentioned in the README in https://gitlab.freedesktop.org/libinput/libei:
> libei does not provide a method for deciding when events should be captured, it merely provides the transport layer for events once that decision has been made.

The new `reis::event::EiEvent` is a higher-level event similar to `ei_event` in libei. Except as a Rust `enum`. Events their have accessors for the `Device` and time (based on `frame` events), similarly to libei.

**Comment by feschber** [comment] 2024-01-04 14:39
Oh I remember reading this at some point, now that you mentioned it. I still think this could be stated a bit more clearly ...

**Comment by feschber** [comment] 2024-03-17 07:42
Any updates?
The input capture portal in ashpd is now working for my intents and purposes and the current status of reis would be absolutely fine for what I need.

**Comment by ids1024** [comment] 2024-03-18 17:02
There are a few things I wanted to fix in `EiEventConverter` before releasing a version with it. But they're fairly simple details, so I've pushed a few commits for that. Some of the server-side/EIS abstractions are a bit more incomplete, but if needed I could just disable those modules for now in a release.

Although the API could still use some (breaking) improvements, the client-side APIs should be fairly functional and usable. Could be good to add as an example in ashpd. So yeah, it's probably good to do a release with them.

**Comment by ids1024** [comment] 2024-03-21 02:32
I've marked the less complete (server-side/calloop) APIs as `#[doc(hidden)]` for now. The non-hidden APIs should be pretty usable. (Though error types could be improved, there should be some higher level API for sending requests, etc.)

This is now released as version 0.2 on crates.io.

**Comment by feschber** [comment] 2024-03-21 11:39
Awesome, thank you :)

**Closed** 2024-03-22 15:02 UTC
